### Welcome to Jekyll Webpack Boilerplate
#
# This config file contains the config of your webpages
# You may also want to update /config/webpack.pwa.js in case you want to generate a Progressive Web App

title: Bytii
email: gilad@011.ninja
description: A super website made with love
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
theme_color: '#000000'
twitter_username: 
github_username:  giladx
author: Gilad Levi
logo: assets/images/large-logo.png
twitter:
  username: giladx
social:
  name: Gilad Levi
  links:
    - https://twitter.com/bytii_cloud
    - https://www.facebook.com/giladx
    - https://www.linkedin.com/in/giladx
    - https://plus.google.com/giladx
    - https://github.com/giladx

languages: ["en","he"]
ampdir: amp
netlify_cms: false

### Google webmaster tools, Google Analytics, Doorbell and Cookie consent uncomment and put the API key
#webmaster_verifications:
#  google: verification_code
#google_analytics: id
#doorbell:
#  id: doorbell_id
#  appKey: doorbell_appKey

#cookie_consent: true

### Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - octopress-minify-html
  - jekyll-multiple-languages-plugin
  - amp-jekyll

### Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - _src
  - _images
  - LICENSE
  - package.json
  - README.md
  - webpack.config.js
  - yarn-error.log
  - yarn.lock
  - config
  - optimization-fix
  - optimization-fix-this-file-is-ignored.js
  - icon.png
